services:
  jdmmarketplace.services.catalogapi:
    image: ${DOCKER_REGISTRY-}jdmmarketplaceservicescatalogapi
    build:
      context: .
      dockerfile: JdmMarketplace.API/Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: catalogDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: